# -*- coding: utf-8 -*-
"""
Created on Sat Mar 28 03:07:34 2020

@author: Gagan

Following code is used to plot graph for model training in Task 2.
This code plots the ariation of "Cost" with respect to "Number of Iterations"
"""

import numpy as np
import matplotlib.pyplot as plt

# INPUTS
# File Path of the file containing the (list of costs) generated by task 2 (Training of Logistic Regression Model)
filePath = 'docs/Assignment_4_Final_List_of_Cost_part-00000'
# Number of iterations for which the model was trained in task 2
numberOfIterationsModelTrained = 203

# Open the file and read it
with open(filePath) as file:
    allLines = file.read()
# Split the file using 'new line' as the separater    
listOfLines = allLines.split('\n')

# Convert the elements (cost) of above list to float
listOfCosts = [float(line) for line in listOfLines[:len(listOfLines)-1]]

# Plot ['Cost' vs 'Number of Iterations']
plt.plot(np.arange(numberOfIterationsModelTrained),listOfCosts)
plt.xlabel('Number of Iterations')
plt.ylabel('Cost')
plt.title('Variation of "Cost" with respect to "Number of Iterations"')

# Save the plot
plt.savefig('docs/Cost_Vs_Iterations_Model_trainingData_task2.png')
